.config/nvim/plugin/ycm.vim: Force YCM to use Python 3.
Else you get the dreaded:

    ImportError: dynamic module does not define init function (initycm_core)

See also:

    :h ImportError
    :h g:ycm_path_to_python_interpreter
    https://github.com/Valloric/YouCompleteMe#i-get-importerror-exceptions-that-mention-pyinit_ycm_core-or-initycm_core